### ISSUE TITLE
Unable to select points through any of your apps

### ISSUE THREAD

**Issue by soulslicer** [taketwo/tcs#5]
I notice the following commands don't work.

I have PCL 1.8.0 compiled from source. 

Hitting Shift and trying to select points simply does not work. There is no response either from the terminal or the GUI. Attempting to drag and select points does not work either, (through pressing X rubber band mode).

I tested this on both the gui and the app random walker

Are you able to compile it and test it on your end?

**Comment by taketwo** [comment]
Seed picking in the GUI version works on my end. However, in the "app" version it is not possible to pick seeds indeed. In fact, it's the visualization of graph vertices that is not working. And since graph vertices are not visible, it is not possible to select them. I'll have a look.

**Comment by taketwo** [comment]
I finally found time to check this out and fix today. If it is still relevant for you, give the latest version a try. And make sure to run `git submodule update` after pulling.
