### ISSUE TITLE
Performing segmentation without initial seeds?

### ISSUE THREAD

**Issue by soulslicer** [taketwo/tcs#6]
Good day,

I briefly read through the paper related to this work. I note the only time seeds were mentioned were when referencing previous work, or about seed resolutions. Does your system actually allow one to automatically figure out seed points?

**Comment by taketwo** [comment]
This repository contains implementation of Random Walker algorithm for semi-automatic point cloud segmentation, so you need to provide seeds. The paper you probably referring to is about spectral clustering, but this repository has nothing to do with it.
