### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by enemy537** [taketwo/tcs#7]
I tried compiling (following instruction) and got this:

/home/avell/tcs/src/segmentation_evaluation.cpp:11:29: fatal error: tviewer/tviewer.h: No such file or directory
compilation terminated.
CMakeFiles/segmentation_evaluation.dir/build.make:62: recipe for target 'CMakeFiles/segmentation_evaluation.dir/src/segmentation_evaluation.cpp.o' failed
make[2]: *** [CMakeFiles/segmentation_evaluation.dir/src/segmentation_evaluation.cpp.o] Error 1
CMakeFiles/Makefile2:168: recipe for target 'CMakeFiles/segmentation_evaluation.dir/all' failed

Ubuntu 16.04
PCL 1.8
VTK 6.2
Boost 1.5.8

**Comment by taketwo** [comment]
Are you sure you used `--recursive` while cloning the repo?

**Comment by enemy537** [comment]
Yes, this is the directory tree.

├── cmake
│   └── Modules
│       └── UseDoxygen.cmake
├── CMakeLists.txt
├── data
│   ├── test13.pcd
│   ├── test1.pcd
│   ├── test47.pcd
│   ├── test56.pcd
│   ├── test60.pcd
│   └── viewpoint.cam
├── Doxyfile.in
├── gui
│   ├── CMakeLists.txt
│   ├── gui.pro
│   ├── main.cpp
│   ├── main_window.cpp
│   ├── main_window.h
│   ├── main_window.ui
│   ├── seed_selection.cpp
│   └── seed_selection.h
├── include
│   ├── as_range.h
│   ├── conversions.h
│   ├── factory
│   │   ├── edge_weight_computer_factory.h
│   │   ├── factory.h
│   │   ├── graph_builder_factory.h
│   │   └── graph_factory.h
│   ├── graph
│   │   ├── common.h
│   │   ├── edge_weight_computer.h
│   │   ├── edge_weight_computer_terms.h
│   │   ├── graph_builder.h
│   │   ├── impl
│   │   │   ├── common.hpp
│   │   │   ├── edge_weight_computer.hpp
│   │   │   ├── nearest_neighbors_graph_builder.hpp
│   │   │   └── voxel_grid_graph_builder.hpp
│   │   ├── nearest_neighbors_graph_builder.h
│   │   ├── point_cloud_graph_concept.h
│   │   ├── point_cloud_graph.h
│   │   ├── utils.h
│   │   └── voxel_grid_graph_builder.h
│   ├── graph_visualizer.h
│   ├── hungarian
│   │   └── hungarian.h
│   ├── impl
│   │   ├── io.hpp
│   │   ├── octree_pointcloud_adjacency3.hpp
│   │   ├── octree_pointcloud_adjacency_container2.hpp
│   │   ├── random_walker.hpp
│   │   └── random_walker_segmentation.hpp
│   ├── io.h
│   ├── label_utils.h
│   ├── measure_runtime.h
│   ├── random_walker.h
│   ├── random_walker_segmentation.h
│   ├── scaler.h
│   ├── seed_utils.h
│   └── typedefs.h
├── README.md
├── src
│   ├── create_seeds.cpp
│   ├── hungarian
│   │   ├── CMakeLists.txt
│   │   └── hungarian.cpp
│   ├── io.cpp
│   ├── random_walker_segmentation_app.cpp
│   ├── random_walker_segmentation.cpp
│   ├── segmentation_evaluation.cpp
│   └── view_point_cloud_graph.cpp
└── third-party
    ├── hungarian-v2.0
    │   ├── Assignment.cpp
    │   ├── Assignment.h
    │   ├── BipartiteGraph.cpp
    │   ├── BipartiteGraph.h
    │   ├── CmdParser.h
    │   ├── example.demo
    │   ├── Hungarian.cpp
    │   ├── Hungarian.h
    │   ├── Log
    │   ├── main.cpp
    │   ├── Makefile
    │   ├── Matrix.h
    │   ├── plot
    │   │   ├── Cgnuplot.cpp
    │   │   ├── Cgnuplot.h
    │   │   ├── graph_hungarian.cpp
    │   │   ├── graph_hungarian.h
    │   │   ├── Makefile
    │   │   └── README
    │   ├── PlotGraph.cpp
    │   ├── PlotGraph.h
    │   └── README
    └── tviewer
        ├── cmake
        │   └── UseDoxygen.cmake
        ├── CMakeLists.txt
        ├── Doxyfile.in
        ├── examples
        │   ├── CMakeLists.txt
        │   ├── example_keyboard_listeners.cpp
        │   └── usage.cpp
        ├── README.md
        └── tviewer
            ├── color.cpp
            ├── color.h
            ├── factory.cpp
            ├── factory.h
            ├── keyboard_listeners
            │   ├── binary_state_switch.cpp
            │   ├── binary_state_switch.h
            │   ├── keyboard_listener.h
            │   ├── up_down_counter.cpp
            │   └── up_down_counter.h
            ├── named_parameters
            │   ├── named_parameters_def.h
            │   └── named_parameters_undef.h
            ├── tviewer.cpp
            ├── tviewer_dummy.h
            ├── tviewer_fwd.h
            ├── tviewer.h
            ├── tviewer_impl.h
            ├── tviewer_interface.h
            ├── tviewer_widget
            │   ├── tviewer_widget.cpp
            │   ├── tviewer_widget.h
            │   └── tviewer_widget.ui
            ├── utils.cpp
            ├── utils.h
            └── visualization_objects
                ├── arrow_array_object.cpp
                ├── arrow_array_object.h
                ├── normal_cloud_object.cpp
                ├── normal_cloud_object.h
                ├── point_cloud_object.cpp
                ├── point_cloud_object.h
                ├── point_cloud_with_color_shuffling_object.cpp
                ├── point_cloud_with_color_shuffling_object.h
                ├── poly_data_object.cpp
                ├── poly_data_object.h
                ├── visualization_object.cpp
                └── visualization_object.h

**Comment by taketwo** [comment]
I could reproduce the issue on my machine. Should be fixed now, please pull the latest changes, including submodules. (Or simply delete the "tsc" directory and recursively clone again.)

**Comment by enemy537** [comment]
Also me! Thank you very much.
