### ISSUE TITLE
QVTKWidget.h: No such file or directory

### ISSUE THREAD

**Issue by shomedas** [taketwo/tcs#8]
I have installed pcl-1.8.1 with vtk6 support(ubuntu 16.04,64bit)
When i try to build tcs code i get fatal error: QVTKWidget.h: No such file or directory
compilation terminated. How do i fix the above error. Do I need to install vtk5? can I install vtk5 with an existing vtk6?

It compiles successfully if I set WITH_QT=OFF and WITH_QT_GUI=OFF

 What functionalities will I miss if I set WITH_QT=OFF and WITH_QT_GUI=OFF

**Comment by taketwo** [comment]
Make sure to install `libvtk6-qt-dev`.

**Comment by taketwo** [comment]
Closing due to lack of response.
